[package]
name = "upowdb-backend"
version = "0.2.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>", "David Lamm <david-lamm@web.de>"]
edition = "2018"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
serde = { version = "1", features = ["derive"] }
clap = "4"
fern = "0.6"
log = "0.4"
actix-web-prom = "0.9"
config = "0.13"
chrono = "0.4"
diesel = { version = "2", features = ["sqlite", "r2d2"] }
futures = "0.3"
serde_json = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
actix-web-jwt-middleware = { path = "actix-web-jwt-middleware" }
rand = "0.8"
regex = "1"
lazy_static = "1"
argon2rs = "0.2.5"
jsonwebtoken = "9"
base64 = "0.21"
actix-web-httpauth = "0.8"
upowdb-models = { path = "upowdb-models" }
futures-util = "0.3"
