open_registration = true
jwt_key = ""
http_timeout = 15000
listen_addr = ["[::]:8082"]
# allowed_frontend = "https://your-frontend-deployment"
db_connection = { type = "sqlite", file = "app.db" }
# db_connection = { type = "postgres", uri = "postgres://postgres:mysecretpassword@localhost/postgres" }
