/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct AccountUpdate {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "new_username", skip_serializing_if = "Option::is_none")]
    pub new_username: Option<String>,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "new_password", skip_serializing_if = "Option::is_none")]
    pub new_password: Option<String>,
}
