/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

/// Course : The root of the Course type's schema.

use serde::{Serialize, Deserialize};
use diesel::{Queryable, Insertable};
use crate::schema::courses;

#[derive(Debug, Serialize, Deserialize)]
pub struct Course {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "worksheets")]
    pub worksheets: Vec<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// CourseSchema is the actual Database Schema represented as struct, whereas Course is the format
/// of the JSON sent by the api TODO: improve the names of these classes

#[derive(Debug, Queryable, Insertable, AsChangeset)]
#[table_name = "courses"]
pub struct CourseSchema {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
}

