/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

/// Database : The root of the Database type's schema.

#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct Database {
    #[serde(rename = "database")]
    pub database: String,
    #[serde(rename = "id")]
    pub id: String,
}

impl Database {
    /// The root of the Database type's schema.
    pub fn new(database: String, id: String) -> Database {
        Database {
            database: database,
            id: id,
        }
    }
}


