/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct McContent {
    #[serde(rename = "answer_options")]
    pub answer_options: Vec<String>,
}

impl McContent {
    pub fn new(answer_options: Vec<String>) -> McContent {
        McContent {
            answer_options: answer_options,
        }
    }
}


