/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct McSolution {
    #[serde(rename = "positions")]
    pub positions: Vec<i64>,
}

impl McSolution {
    pub fn new(positions: Vec<i64>) -> McSolution {
        McSolution {
            positions: positions,
        }
    }
}


