/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct PlaintextSolution {
    #[serde(rename = "text")]
    pub text: String,
}

impl PlaintextSolution {
    pub fn new(text: String) -> PlaintextSolution {
        PlaintextSolution {
            text: text,
        }
    }
}


