/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub enum Solution {
    #[serde(rename = "sql")]
    SQL { columns: Vec<String>, rows: Vec<Vec<String>>, query: String },
    #[serde(rename = "multiple_choice")]
    MultipleChoice { positions: Vec<i64> },
    #[serde(rename = "plaintext")]
    Plaintext { text: String },
    Instruction,
}

impl Solution {
    pub fn new() -> Solution {
        Solution::Instruction
    }
}


