/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub enum Solution {
    SQL(SQLSolution),
    MultipleChoice(MCSolution),
    Text(PlaintextSolution),
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SQLSolution {
    query: String,
    columns: Vec<String>,
    rows: Vec<Vec<String>>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MCSolution {
    correct_positions: Vec<i64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct PlaintextSolution {
    text: String,
}