/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct SqlContent {
    #[serde(rename = "row_order_matters")]
    pub row_order_matters: bool,
}

impl SqlContent {
    pub fn new(row_order_matters: bool) -> SqlContent {
        SqlContent {
            row_order_matters: row_order_matters,
        }
    }
}


