/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};
use diesel::{Insertable, Queryable};
use crate::schema::subtasks;

#[derive(Debug, Serialize, Deserialize, Queryable)]
pub struct Subtask {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "instruction")]
    pub instruction: String,
    #[serde(rename = "solution_verifiable")]
    pub is_solution_verifiable: bool,
    #[serde(rename = "solution_visible")]
    pub is_solution_visible: bool,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<crate::models::Content>,
}