/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Subtask {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "instruction")]
    pub instruction: String,
    #[serde(rename = "solution_verifiable")]
    pub solution_verifiable: bool,
    #[serde(rename = "solution_visible")]
    pub solution_visible: bool,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<crate::models::Content>,
    #[serde(rename = "solution", skip_serializing_if = "Option::is_none")]
    pub solution: Option<crate::models::Solution>,
}