/*
 * dbsquared
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jan.christian@gruenhage.xyz
 * Generated by: https://openapi-generator.tech
 */

use serde::{Serialize, Deserialize};
use diesel::prelude::*;
use crate::schema::worksheets;
use crate::schema::tasks_in_worksheets;

#[derive(Debug, Serialize, Deserialize)]
pub struct Worksheet {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "is_online")]
    pub is_online: bool,
    #[serde(rename = "is_solution_online")]
    pub is_solution_online: bool,
    #[serde(rename = "tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Vec<String>>,
}

#[derive(Queryable, Insertable)]
#[table_name = "worksheets"]
pub struct QueryableWorksheet {
    pub id: String,
    pub name: Option<String>,
    pub is_online: bool,
    pub is_solution_online: bool,
}

#[derive(Debug, Queryable, Insertable)]
pub struct TasksInWorksheet {
    pub task_id: String,
    pub worksheet_id: String,
}